"""ARGUS Web Server.

FastAPI backend that runs scans and streams live events to the browser
via Server-Sent Events. The frontend is a single-page HTML app served
from the static/ directory.

Endpoints:
- GET /                 → dashboard HTML
- GET /api/status       → current scan status snapshot
- POST /api/scan/start  → kick off a new scan
- POST /api/scan/stop   → cancel running scan
- GET /api/events       → SSE stream of all scan events (signal bus + findings)
- GET /api/findings     → all findings from the most recent scan
- GET /api/health       → service liveness

Security:
- API token auth (Bearer) required on all /api/* routes except /api/health.
  Token is auto-generated on startup and printed to the console for the
  operator to use, OR sourced from ARGUS_WEB_TOKEN env var.
- ScanRequest URLs are validated and SSRF-blocked by default — private
  ranges (loopback, link-local, RFC1918) are rejected unless
  ARGUS_WEB_ALLOW_PRIVATE=1 is set (used by the local benchmark).
- CORS is locked down to same-origin by default.
- ScanState is bounded — findings/signals capped to prevent unbounded growth.
- Token comparison uses constant-time compare.
"""

from __future__ import annotations

import asyncio
import ipaddress
import json
import logging
import os
import secrets
import time
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, field_validator
from sse_starlette.sse import EventSourceResponse

from argus.agents import (
    ContextWindowAgent,
    CrossAgentExfilAgent,
    IdentitySpoofAgent,
    MemoryBoundaryCollapseAgent,
    MemoryPoisoningAgent,
    ModelExtractionAgent,
    PersonaHijackingAgent,
    PrivilegeEscalationAgent,
    PromptInjectionHunter,
    RaceConditionAgent,
    SupplyChainAgent,
    ToolPoisoningAgent,
)
from argus.models.agents import AgentType, TargetConfig
from argus.orchestrator.engine import Orchestrator, ScanResult
from argus.orchestrator.signal_bus import Signal, SignalType

logger = logging.getLogger(__name__)

STATIC_DIR = Path(__file__).parent / "static"

# ============================================================
# Security configuration
# ============================================================

# Allow scanning private/loopback ranges. Default OFF — operators must
# explicitly opt in for local benchmark testing. The benchmark runner sets
# this to "1" before starting the server.
ALLOW_PRIVATE_RANGES = os.environ.get("ARGUS_WEB_ALLOW_PRIVATE", "").lower() in ("1", "true", "yes")

# Auth token. Sourced from env or auto-generated.
_TOKEN_FROM_ENV = os.environ.get("ARGUS_WEB_TOKEN", "").strip()
WEB_TOKEN: str = _TOKEN_FROM_ENV or secrets.token_urlsafe(32)
_TOKEN_AUTOGENERATED = not bool(_TOKEN_FROM_ENV)

# Bounded state limits — protects against memory exhaustion from a malicious
# target that emits floods of findings.
MAX_FINDINGS_IN_MEMORY = 10_000
MAX_SIGNALS_IN_MEMORY = 50_000
MAX_RECENT_FINDINGS_RETURNED = 50

# Allowed URL schemes
ALLOWED_URL_SCHEMES = frozenset({"http", "https"})

# Blocked SSRF host patterns when ALLOW_PRIVATE_RANGES is False
SSRF_BLOCKED_EXACT_HOSTS = frozenset(
    {
        "localhost",
        "metadata.google.internal",
        "metadata",
    }
)


_bearer_scheme = HTTPBearer(auto_error=False)


def _validate_url_for_scan(url: str) -> None:
    """Validate a target URL for use in a scan request.

    Raises ValueError if the URL is malformed, uses a forbidden scheme,
    or points to a private/internal address (unless ALLOW_PRIVATE_RANGES).
    """
    if not url or not isinstance(url, str):
        raise ValueError("URL must be a non-empty string")

    parsed = urlparse(url)
    if parsed.scheme not in ALLOWED_URL_SCHEMES:
        raise ValueError(f"URL scheme '{parsed.scheme}' not allowed (use http:// or https://)")
    if not parsed.hostname:
        raise ValueError("URL must have a valid hostname")

    if ALLOW_PRIVATE_RANGES:
        return

    host = parsed.hostname.lower()
    if host in SSRF_BLOCKED_EXACT_HOSTS:
        raise ValueError(f"URL host '{host}' is blocked (private/metadata range)")

    # Check literal IPs first
    try:
        ip = ipaddress.ip_address(host)
        _check_ip_blocked(ip)
        return
    except ValueError as exc:
        if "points to" in str(exc):
            raise
        # Not a literal IP — fall through to DNS resolution

    # Resolve DNS and re-check every returned address. This closes the
    # DNS-rebinding bypass where an attacker registers `evil.example.com`
    # with an A record of 127.0.0.1 / 169.254.169.254 etc.
    # Note: this is best-effort. The real MCP/HTTP client should still
    # validate the resolved address at request time, since DNS responses
    # can change between this check and the actual connect.
    import socket as _socket

    try:
        infos = _socket.getaddrinfo(host, None)
    except OSError as exc:
        raise ValueError(f"URL host '{host}' could not be resolved: {type(exc).__name__}") from None

    for info in infos:
        addr = info[4][0]
        try:
            resolved_ip = ipaddress.ip_address(addr)
        except ValueError:
            continue
        _check_ip_blocked(resolved_ip)


def _check_ip_blocked(ip: ipaddress.IPv4Address | ipaddress.IPv6Address) -> None:
    """Raise ValueError if an IP address is in a blocked range."""
    if ip.is_loopback or ip.is_link_local or ip.is_private or ip.is_reserved or ip.is_multicast:
        raise ValueError(f"URL points to blocked IP range: {ip}")
    if str(ip) in ("169.254.169.254", "169.254.170.2"):
        raise ValueError(f"URL points to cloud metadata endpoint: {ip}")


class ScanRequest(BaseModel):
    """Request body for starting a scan."""

    target_name: str = "Untitled Target"
    mcp_urls: list[str] = []
    agent_endpoint: str | None = None
    timeout: float = 300.0
    demo_pace_seconds: float = 0.4

    @field_validator("mcp_urls")
    @classmethod
    def _validate_mcp_urls(cls, v: list[str]) -> list[str]:
        if len(v) > 50:
            raise ValueError("Too many MCP URLs (max 50)")
        for url in v:
            try:
                _validate_url_for_scan(url)
            except ValueError as exc:
                raise ValueError(f"Invalid MCP URL '{url}': {exc}") from exc
        return v

    @field_validator("agent_endpoint")
    @classmethod
    def _validate_agent_endpoint(cls, v: str | None) -> str | None:
        if v is None:
            return v
        try:
            _validate_url_for_scan(v)
        except ValueError as exc:
            raise ValueError(f"Invalid agent endpoint '{v}': {exc}") from exc
        return v

    @field_validator("timeout")
    @classmethod
    def _validate_timeout(cls, v: float) -> float:
        if v < 1.0 or v > 1800.0:
            raise ValueError("timeout must be between 1 and 1800 seconds")
        return v

    @field_validator("demo_pace_seconds")
    @classmethod
    def _validate_demo_pace(cls, v: float) -> float:
        if v < 0.0 or v > 10.0:
            raise ValueError("demo_pace_seconds must be between 0 and 10")
        return v

    @field_validator("target_name")
    @classmethod
    def _validate_target_name(cls, v: str) -> str:
        if len(v) > 200:
            raise ValueError("target_name too long (max 200 chars)")
        return v


# ============================================================
# Auth dependency
# ============================================================


async def require_token(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer_scheme),
) -> None:
    """Bearer token authentication for /api/* routes.

    Uses constant-time compare to prevent timing attacks.
    """
    if credentials is None or credentials.scheme.lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Bearer token required",
            headers={"WWW-Authenticate": "Bearer"},
        )
    if not secrets.compare_digest(credentials.credentials, WEB_TOKEN):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token",
            headers={"WWW-Authenticate": "Bearer"},
        )


class ScanState:
    """In-memory state for the currently running (or last) scan."""

    def __init__(self) -> None:
        self.scan_id: str | None = None
        self.target_name: str = ""
        self.target_endpoints: list[str] = []
        self.started_at: float | None = None
        self.completed_at: float | None = None
        self.status: str = "idle"  # idle, running, completed, failed
        self.agents: dict[str, dict[str, Any]] = {}
        self.findings: list[dict[str, Any]] = []
        self.signals: list[dict[str, Any]] = []
        self.events_queue: asyncio.Queue[dict[str, Any]] = asyncio.Queue()
        self.subscribers: list[asyncio.Queue[dict[str, Any]]] = []
        self.scan_task: asyncio.Task | None = None
        self.orchestrator: Orchestrator | None = None
        self.last_result: ScanResult | None = None

    def reset(self) -> None:
        self.scan_id = None
        self.target_name = ""
        self.target_endpoints = []
        self.started_at = None
        self.completed_at = None
        self.status = "idle"
        self.agents = {}
        self.findings = []
        self.signals = []
        # Don't clear subscribers — they're long-lived

    def add_finding(self, finding_data: dict[str, Any]) -> None:
        """Append a finding with bounded memory."""
        self.findings.append(finding_data)
        if len(self.findings) > MAX_FINDINGS_IN_MEMORY:
            # Keep most recent N findings — drop oldest
            self.findings = self.findings[-MAX_FINDINGS_IN_MEMORY:]

    def add_signal(self, signal: dict[str, Any]) -> None:
        """Append a signal with bounded memory."""
        self.signals.append(signal)
        if len(self.signals) > MAX_SIGNALS_IN_MEMORY:
            self.signals = self.signals[-MAX_SIGNALS_IN_MEMORY:]

    @property
    def elapsed_seconds(self) -> float:
        if self.started_at is None:
            return 0.0
        end = self.completed_at or time.monotonic()
        return end - self.started_at

    @property
    def total_findings(self) -> int:
        return len(self.findings)

    @property
    def validated_findings(self) -> int:
        return sum(1 for f in self.findings if f.get("status") == "validated")

    @property
    def agents_running(self) -> int:
        return sum(1 for a in self.agents.values() if a.get("status") == "running")

    @property
    def agents_completed(self) -> int:
        return sum(1 for a in self.agents.values() if a.get("status") == "completed")

    def snapshot(self) -> dict[str, Any]:
        return {
            "scan_id": self.scan_id,
            "target_name": self.target_name,
            "target_endpoints": self.target_endpoints,
            "status": self.status,
            "elapsed_seconds": round(self.elapsed_seconds, 2),
            "total_findings": self.total_findings,
            "validated_findings": self.validated_findings,
            "agents_running": self.agents_running,
            "agents_completed": self.agents_completed,
            "agents_total": len(self.agents),
            "agents": self.agents,
            "recent_findings": self.findings[-MAX_RECENT_FINDINGS_RETURNED:],
            "signal_count": len(self.signals),
        }

    async def broadcast(self, event_type: str, payload: Any) -> None:
        """Push an event to all SSE subscribers."""
        event = {"type": event_type, "data": payload, "ts": time.time()}
        # Push to all live subscribers
        for queue in list(self.subscribers):
            try:
                queue.put_nowait(event)
            except asyncio.QueueFull:
                pass


def create_app() -> FastAPI:
    """Create and configure the ARGUS FastAPI application."""
    app = FastAPI(
        title="ARGUS Web Dashboard",
        description="Autonomous AI Red Team Platform — live web dashboard",
        version="0.1.0",
    )

    # Same-origin only by default — explicitly tighten CORS.
    # Operators who need cross-origin can set ARGUS_WEB_ALLOW_ORIGIN.
    extra_origin = os.environ.get("ARGUS_WEB_ALLOW_ORIGIN", "").strip()
    allow_origins = [
        "http://127.0.0.1:8765",
        "http://localhost:8765",
        "http://127.0.0.1:5173",
        "http://localhost:5173",
    ]
    if extra_origin:
        allow_origins.append(extra_origin)

    app.add_middleware(
        CORSMiddleware,
        allow_origins=allow_origins,
        allow_credentials=False,
        allow_methods=["GET", "POST", "PUT", "DELETE"],
        allow_headers=["Authorization", "Content-Type"],
    )

    state = ScanState()
    app.state.scan_state = state

    if _TOKEN_AUTOGENERATED:
        logger.info("ARGUS Web auth token (auto-generated): %s", WEB_TOKEN)
        logger.info("Set ARGUS_WEB_TOKEN env var to provide your own token")
    else:
        logger.info("ARGUS Web auth token sourced from ARGUS_WEB_TOKEN env var")

    if ALLOW_PRIVATE_RANGES:
        logger.warning(
            "ARGUS_WEB_ALLOW_PRIVATE=1 — ScanRequest URLs to private/loopback ranges WILL be accepted. "
            "Only use this for local benchmark testing."
        )

    # Initialize database and mount production API routes
    try:
        from argus.db.session import init_db
        from argus.web.api_routes import create_production_router

        init_db()
        app.include_router(create_production_router())
        logger.info("Production API routes mounted (targets, scans, auth, reports)")
    except Exception as exc:
        logger.warning("Could not initialize production routes: %s", type(exc).__name__)

    # Mount callback beacon router (no auth — targets call back here)
    try:
        from argus.beacon.server import create_beacon_router

        app.include_router(create_beacon_router(auth_dependency=require_token))
        logger.info("Beacon callback router mounted at /beacon/")
    except Exception as exc:
        logger.warning("Could not initialize beacon router: %s", type(exc).__name__)

    # Mount static assets
    if STATIC_DIR.exists():
        app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

    # ------------------------------------------------------------------
    # Page routes
    # ------------------------------------------------------------------

    @app.get("/")
    async def index(request: Request) -> Response:
        """Serve dashboard HTML with the auth token injected.

        The token is only injected for requests from loopback (127.0.0.1 / ::1).
        Browsers loading the page over loopback are trusted; cross-network
        loads must supply the token via Authorization header manually.
        """
        client_host = request.client.host if request.client else ""
        is_loopback = client_host in ("127.0.0.1", "::1", "localhost")

        try:
            html = (STATIC_DIR / "index.html").read_text(encoding="utf-8")
        except OSError:
            raise HTTPException(status_code=500, detail="Dashboard HTML missing") from None

        if is_loopback:
            # Inject the token into a meta tag the JS will read.
            # HTML-escape the token: auto-generated tokens are safe, but an
            # operator-supplied ARGUS_WEB_TOKEN containing quotes would
            # otherwise break out of the attribute and enable stored XSS.
            from html import escape as _html_escape

            safe_token = _html_escape(WEB_TOKEN, quote=True)
            token_meta = f'<meta name="argus-token" content="{safe_token}">'
            html = html.replace("</head>", f"  {token_meta}\n</head>", 1)

        return Response(content=html, media_type="text/html")

    # ------------------------------------------------------------------
    # API routes — public health, all others require auth
    # ------------------------------------------------------------------

    @app.get("/api/health")
    async def health() -> dict[str, str]:
        # Public — no auth required
        return {"status": "ok", "service": "argus-web", "version": "0.1.0"}

    @app.get("/api/status", dependencies=[Depends(require_token)])
    async def status_ep() -> Response:
        body = json.dumps(state.snapshot(), default=str)
        return Response(content=body, media_type="application/json")

    @app.get("/api/findings", dependencies=[Depends(require_token)])
    async def findings() -> Response:
        body = json.dumps({"findings": state.findings}, default=str)
        return Response(content=body, media_type="application/json")

    @app.post("/api/scan/start", dependencies=[Depends(require_token)])
    async def scan_start(request: ScanRequest) -> dict[str, Any]:
        if state.status == "running":
            raise HTTPException(status_code=409, detail="Scan already running")

        state.reset()
        state.target_name = request.target_name
        state.target_endpoints = list(request.mcp_urls)
        if request.agent_endpoint:
            state.target_endpoints.append(request.agent_endpoint)
        state.status = "running"
        state.started_at = time.monotonic()

        # Generate scan_id eagerly so it's available in the response
        # before the background task starts executing.
        import uuid

        scan_id = str(uuid.uuid4())
        state.scan_id = scan_id

        target = TargetConfig(
            name=request.target_name,
            mcp_server_urls=request.mcp_urls,
            agent_endpoint=request.agent_endpoint,
            non_destructive=True,
            max_requests_per_minute=120,
        )

        orchestrator = Orchestrator()
        # Phase 1
        orchestrator.register_agent(AgentType.PROMPT_INJECTION, PromptInjectionHunter)
        orchestrator.register_agent(AgentType.TOOL_POISONING, ToolPoisoningAgent)
        orchestrator.register_agent(AgentType.SUPPLY_CHAIN, SupplyChainAgent)
        # Phase 2
        orchestrator.register_agent(AgentType.MEMORY_POISONING, MemoryPoisoningAgent)
        orchestrator.register_agent(AgentType.IDENTITY_SPOOF, IdentitySpoofAgent)
        # Phase 3
        orchestrator.register_agent(AgentType.CONTEXT_WINDOW, ContextWindowAgent)
        orchestrator.register_agent(AgentType.CROSS_AGENT_EXFIL, CrossAgentExfilAgent)
        orchestrator.register_agent(AgentType.PRIVILEGE_ESCALATION, PrivilegeEscalationAgent)
        orchestrator.register_agent(AgentType.RACE_CONDITION, RaceConditionAgent)
        # Phase 4
        orchestrator.register_agent(AgentType.MODEL_EXTRACTION, ModelExtractionAgent)
        # Phase 5
        orchestrator.register_agent(AgentType.PERSONA_HIJACKING, PersonaHijackingAgent)
        orchestrator.register_agent(AgentType.MEMORY_BOUNDARY_COLLAPSE, MemoryBoundaryCollapseAgent)
        state.orchestrator = orchestrator

        # Initialize agent state cards
        for agent_type in orchestrator.get_registered_agents():
            state.agents[agent_type.value] = {
                "type": agent_type.value,
                "status": "pending",
                "findings_count": 0,
                "validated_count": 0,
                "current_action": "Waiting to deploy...",
                "techniques_attempted": 0,
                "started_at": None,
                "completed_at": None,
            }

        # Subscribe handler to capture signal bus events
        async def signal_handler(signal: Signal) -> None:
            state.add_signal(
                {
                    "type": signal.signal_type.value,
                    "source_agent": signal.source_agent,
                    "ts": signal.timestamp.isoformat(),
                }
            )

            agent_id = signal.source_agent
            if agent_id in state.agents:
                agent = state.agents[agent_id]

                if signal.signal_type == SignalType.AGENT_STATUS:
                    new_status = signal.data.get("status", "")
                    if new_status == "running":
                        agent["status"] = "running"
                        agent["started_at"] = time.time()
                        agent["current_action"] = "Deployed — beginning attack..."
                    elif new_status == "completed":
                        agent["status"] = "completed"
                        agent["completed_at"] = time.time()
                        agent["current_action"] = "Mission complete"

                elif signal.signal_type == SignalType.FINDING:
                    finding_data = signal.data.get("finding", {})
                    agent["findings_count"] += 1
                    if finding_data.get("status") == "validated":
                        agent["validated_count"] += 1
                    title = finding_data.get("title", "")
                    agent["current_action"] = f"Found: {title[:80]}"

                    # Truncate raw_request/raw_response before broadcasting on
                    # SSE — large target responses can blow out browser memory
                    # and may contain PII the operator does not want streamed.
                    # The full body remains in the in-memory finding for export.
                    sse_data = dict(finding_data)
                    for key in ("raw_request", "raw_response"):
                        v = sse_data.get(key)
                        if isinstance(v, str) and len(v) > 5000:
                            sse_data[key] = v[:5000] + "...[truncated for SSE]"

                    state.add_finding(finding_data)
                    await state.broadcast("finding", sse_data)

                elif signal.signal_type == SignalType.PARTIAL_FINDING:
                    data_summary = str(signal.data.get("type", "probing"))[:60]
                    agent["current_action"] = f"Probing: {data_summary}"

            await state.broadcast("signal", state.snapshot())

        await orchestrator.signal_bus.subscribe_broadcast(signal_handler)

        # Run the scan in the background
        async def _run() -> None:
            try:
                result = await orchestrator.run_scan(
                    target=target,
                    scan_id=scan_id,
                    timeout=request.timeout,
                    demo_pace_seconds=request.demo_pace_seconds,
                )
                state.last_result = result
                state.status = "completed"
                state.completed_at = time.monotonic()

                # Persist scan results to database
                try:
                    from argus.db.scan_persistence import ScanPersistence

                    persistence = ScanPersistence()
                    try:
                        persistence.save(
                            scan_result=result,
                            target_name=request.target_name,
                            initiated_by="web_dashboard",
                        )
                    finally:
                        persistence.close()
                    logger.info("Scan %s persisted to database", result.scan_id[:8])
                except Exception as persist_exc:
                    logger.warning("Failed to persist scan: %s", type(persist_exc).__name__)

                await state.broadcast("complete", state.snapshot())
            except Exception as exc:
                logger.exception("Scan failed: %s", type(exc).__name__)
                state.status = "failed"
                state.completed_at = time.monotonic()
                await state.broadcast("failed", {"error": type(exc).__name__})

        state.scan_task = asyncio.create_task(_run())

        await state.broadcast("scan_started", state.snapshot())
        return {"status": "started", "scan_id": state.scan_id}

    @app.post("/api/scan/stop", dependencies=[Depends(require_token)])
    async def scan_stop() -> dict[str, str]:
        if state.scan_task and not state.scan_task.done():
            state.scan_task.cancel()
            state.status = "cancelled"
            state.completed_at = time.monotonic()
            await state.broadcast("cancelled", state.snapshot())
            return {"status": "cancelled"}
        return {"status": "no_active_scan"}

    @app.get("/api/events")
    async def events(request: Request) -> EventSourceResponse:
        """SSE stream of all scan events for the dashboard frontend.

        Auth: bearer token via Authorization header OR ?token= query param
        (EventSource cannot send custom headers in browsers).
        """
        # Validate token from header or query param
        auth_header = request.headers.get("authorization", "")
        token_from_header = ""
        if auth_header.lower().startswith("bearer "):
            token_from_header = auth_header[7:].strip()
        token_from_query = request.query_params.get("token", "")
        provided = token_from_header or token_from_query
        if not provided or not secrets.compare_digest(provided, WEB_TOKEN):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Bearer token required (Authorization header or ?token= query)",
            )

        queue: asyncio.Queue[dict[str, Any]] = asyncio.Queue(maxsize=1000)
        state.subscribers.append(queue)

        async def event_generator():
            try:
                # Send initial snapshot
                yield {
                    "event": "snapshot",
                    "data": json.dumps(state.snapshot(), default=str),
                }

                while True:
                    try:
                        event = await asyncio.wait_for(queue.get(), timeout=15.0)
                        yield {
                            "event": event["type"],
                            "data": json.dumps(event["data"], default=str),
                        }
                    except TimeoutError:
                        # Heartbeat to keep connection alive
                        yield {"event": "ping", "data": "{}"}
            finally:
                if queue in state.subscribers:
                    state.subscribers.remove(queue)

        return EventSourceResponse(event_generator())

    return app
