"""ARGUS persistent configuration — reads/writes ~/.argusrc for API keys and defaults.

Supports three layers (highest priority wins):
  1. CLI flags (--agent-api-key, etc.)
  2. Environment variables (ANTHROPIC_API_KEY, OPENAI_API_KEY, etc.)
  3. Config file (~/.argusrc) — TOML format

Security: config file is created with 0600 permissions (owner read/write only).
API key values are never logged or printed in full — only the last 4 chars.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Config location
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG_DIR = Path.home() / ".argus"
_DEFAULT_CONFIG_FILE = _DEFAULT_CONFIG_DIR / "argusrc"


def _config_path() -> Path:
    """Return the path to the config file, respecting ARGUS_CONFIG_PATH override."""
    override = os.environ.get("ARGUS_CONFIG_PATH")
    if override:
        return Path(override)
    return _DEFAULT_CONFIG_FILE


# ---------------------------------------------------------------------------
# Low-level read / write
# ---------------------------------------------------------------------------


def _read_config() -> dict[str, Any]:
    """Read the TOML config file. Returns empty dict if missing or unreadable."""
    path = _config_path()
    if not path.exists():
        return {}
    try:
        import tomllib  # Python 3.11+

        with open(path, "rb") as f:
            return tomllib.load(f)
    except ImportError:
        # Fallback: simple key=value parser for environments without tomllib
        return _read_simple(path)
    except Exception:
        return {}


def _read_simple(path: Path) -> dict[str, Any]:
    """Minimal key=value parser as fallback when tomllib is unavailable."""
    result: dict[str, Any] = {}
    current_section: dict[str, Any] = result
    try:
        for line in path.read_text().splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("[") and stripped.endswith("]"):
                section_name = stripped[1:-1].strip()
                result.setdefault(section_name, {})
                current_section = result[section_name]
                continue
            if "=" in stripped:
                key, _, value = stripped.partition("=")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                current_section[key] = value
    except Exception:
        return result
    return result


def _escape_toml_value(s: str) -> str:
    """Escape a string for use inside a TOML basic (double-quoted) string."""
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\r", "\\r")
    s = s.replace("\t", "\\t")
    return s


def _write_config(data: dict[str, Any]) -> None:
    """Write the config dict as TOML to the config file with secure permissions."""
    path = _config_path()
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# ARGUS Configuration",
        "# Generated by: argus config set",
        "# Docs: https://github.com/Odingard/Argus",
        "",
    ]

    # Write top-level keys first
    for key, value in sorted(data.items()):
        if isinstance(value, dict):
            continue
        lines.append(f'{key} = "{_escape_toml_value(str(value))}"')

    # Write sections
    for section, values in sorted(data.items()):
        if not isinstance(values, dict):
            continue
        lines.append("")
        lines.append(f"[{section}]")
        for key, val in sorted(values.items()):
            lines.append(f'{key} = "{_escape_toml_value(str(val))}"')

    lines.append("")
    content = "\n".join(lines)

    # Write with secure permissions atomically — avoid world-readable window
    try:
        fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            os.write(fd, content.encode())
        finally:
            os.close(fd)
    except OSError:
        # Fallback for platforms without os.open support (e.g. some Windows)
        path.write_text(content)
        try:
            path.chmod(stat.S_IRUSR | stat.S_IWUSR)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# Public API — get / set / delete / list
# ---------------------------------------------------------------------------

# Well-known config keys and their env-var equivalents
_KEY_MAP: dict[str, str] = {
    "anthropic_api_key": "ANTHROPIC_API_KEY",
    "openai_api_key": "OPENAI_API_KEY",
    "google_api_key": "GOOGLE_API_KEY",
    "custom_api_key": "ARGUS_CUSTOM_API_KEY",
    "custom_endpoint": "ARGUS_CUSTOM_ENDPOINT",
    "agent_api_key": "ARGUS_AGENT_API_KEY",
    "default_timeout": "ARGUS_TIMEOUT",
    "default_max_rpm": "ARGUS_MAX_RPM",
}


def get(key: str) -> str | None:
    """Get a config value. Priority: env var > config file."""
    env_name = _KEY_MAP.get(key)
    if env_name:
        env_val = os.environ.get(env_name)
        if env_val:
            return env_val

    data = _read_config()
    # Check [keys] section for API keys
    keys_section = data.get("keys", {})
    if key in keys_section:
        return str(keys_section[key])
    # Check [defaults] section
    defaults_section = data.get("defaults", {})
    if key in defaults_section:
        return str(defaults_section[key])
    # Check top-level
    if key in data and not isinstance(data[key], dict):
        return str(data[key])

    return None


def set_value(key: str, value: str) -> None:
    """Set a config value in the config file."""
    data = _read_config()

    # Route API keys to [keys] section, others to [defaults]
    if key.endswith("_api_key") or key.endswith("_key"):
        data.setdefault("keys", {})[key] = value
    elif key.startswith("default_"):
        data.setdefault("defaults", {})[key] = value
    else:
        data[key] = value

    _write_config(data)


def delete(key: str) -> bool:
    """Delete a config key. Returns True if key existed."""
    data = _read_config()
    found = False

    for section_name in ["keys", "defaults"]:
        section = data.get(section_name, {})
        if key in section:
            del section[key]
            found = True

    if key in data and not isinstance(data.get(key), dict):
        del data[key]
        found = True

    if found:
        _write_config(data)
    return found


def list_all() -> dict[str, str]:
    """List all config values (from file only, not env)."""
    data = _read_config()
    result: dict[str, str] = {}

    for key, value in data.items():
        if isinstance(value, dict):
            for sub_key, sub_val in value.items():
                result[sub_key] = str(sub_val)
        else:
            result[key] = str(value)

    return result


def mask_key(value: str) -> str:
    """Mask an API key for display — show only last 4 chars."""
    if len(value) <= 4:
        return "****"
    return "***" + value[-4:]


# ---------------------------------------------------------------------------
# Integration helpers — used by CLI and orchestrator
# ---------------------------------------------------------------------------


def resolve_llm_api_key() -> str | None:
    """Resolve the LLM API key from env or config. Anthropic checked first."""
    return get("anthropic_api_key") or get("openai_api_key") or get("google_api_key") or get("custom_api_key")


def resolve_agent_api_key(cli_value: str | None = None) -> str | None:
    """Resolve the target agent API key. CLI flag > env > config."""
    if cli_value:
        return cli_value
    return get("agent_api_key")
